# Hệ gợi ý việc làm trực tuyến
## Thực hành AI Engine và catalog 500 tin bằng Jupyter Notebook

**Mục tiêu:** gợi ý việc tương tự, ghép CV theo vị trí/kỹ năng/lĩnh vực/mô tả,
và lọc nơi muốn làm việc. Notebook dùng các lớp Python chung với web Streamlit.

Tải toàn bộ repo, cài thư viện theo README, chọn kernel Python rồi dùng
**Restart Kernel and Run All Cells**. Mặc định TF-IDF chạy offline với catalog
đã có trong repo. Phần cuối bổ sung hybrid và đánh giá pilot A/B/C với nhãn còn cần rà soát độc lập.

### 1. Nạp thư viện và chọn cấu hình

Cài môi trường theo README trước khi chạy. Nếu báo thiếu module, kiểm tra kernel đã chọn.
`LANGUAGE = "vi"` sử dụng tin và CV tiếng Việt; đổi thành `"en"` để dùng dữ liệu tiếng Anh.
Mỗi lần đổi cấu hình, chạy lại các ô bên dưới theo thứ tự.

In [1]:
from pathlib import Path
import json
import inspect

import numpy as np
import pandas as pd
from IPython.display import display, Markdown, Code
from sklearn.metrics.pairwise import cosine_similarity

# Notebook đặt cùng thư mục với hai module này để tái sử dụng mã OOP đã viết.
from generate_mock_data import MockDataGenerator, JOB_COLUMNS
from job_recommender import JobRecommenderSystem, TextPreprocessor, TfidfTextVectorizer
from catalog_data import localize_jobs
from resume_profile import ResumeAnalyzer

LANGUAGE = "vi"                  # "vi" hoặc "en"
BACKEND = "tfidf"                # Hoặc "sentence-transformers" sau khi cài thêm thư viện
JOB_ID = None                    # None: tự chọn một tin phân tích dữ liệu
TARGET_REGION = "ha_noi"          # Vùng đã xác nhận; None: tất cả vùng
TOP_N = 5

if LANGUAGE not in {"vi", "en"}:
    raise ValueError("LANGUAGE phải là 'vi' hoặc 'en'.")

DATA_DIR = Path("data")
pd.set_option("display.max_colwidth", 100)
print(f"Ngôn ngữ: {LANGUAGE}; backend: {BACKEND}; top_n: {TOP_N}")

Ngôn ngữ: vi; backend: tfidf; top_n: 5

### 2. Đọc và kiểm tra dữ liệu

Ưu tiên `data/jobs_catalog.csv`: 500 tin IT được chọn từ dataset công khai của
TiniX AI (CC BY-NC 4.0), có công ty, lương, vùng và provenance. Hai ngôn ngữ là
hai cách hiển thị cùng tin; bản Anh có thể là tóm tắt có cấu trúc, không phải
bản dịch toàn văn. Chi tiết tại `data/DATA_SOURCE.md` và `catalog_manifest.json`.

`MockDataGenerator` và 20 tin cũ vẫn dùng để minh họa/kiểm thử khi không có catalog.
Chỉ 6 cột gốc là bắt buộc; metadata được giữ trong engine để lọc vùng và hiển thị.

In [2]:
generator = MockDataGenerator()
DATA_DIR.mkdir(parents=True, exist_ok=True)
catalog = DATA_DIR / "jobs_catalog.csv"
if catalog.exists():
    jobs_path = catalog
    jobs = localize_jobs(pd.read_csv(catalog, encoding="utf-8-sig", dtype={"Job_ID": str}), LANGUAGE)
else:
    vi_path = DATA_DIR / "jobs_vie.csv"
    jobs_path = (vi_path if vi_path.exists() else DATA_DIR / "jobs_vie.cvs") if LANGUAGE == "vi" else DATA_DIR / "jobs.csv"
    jobs = pd.read_csv(jobs_path, encoding="utf-8-sig", dtype={"Job_ID": str}) if jobs_path.exists() else (generator.create_vietnamese_jobs() if LANGUAGE == "vi" else generator.create_jobs())

assert set(JOB_COLUMNS).issubset(jobs.columns)
assert len(jobs) >= 15 and jobs["Job_ID"].is_unique
assert jobs[JOB_COLUMNS].notna().all().all()
if JOB_ID is None:
    analytical = jobs[jobs["Role_Code"] == "data_analyst"] if "Role_Code" in jobs else jobs.iloc[:1]
    JOB_ID = (analytical if not analytical.empty else jobs).iloc[0]["Job_ID"]
print(f"Đã đọc {len(jobs)} việc làm từ {jobs_path.as_posix()}; tin thử: {JOB_ID}")
display(jobs.head(10))

Đã đọc 500 việc làm từ data/jobs_catalog.csv; tin thử: VN0016

,Job_ID,Title,Skills,Experience_Years,Domain,Job_Description,Title_EN,Experience_Known,Experience_Text,Domain_EN,...,Source_License,Source_URL,Content_Fingerprint,Experience_Source,Experience_Evidence,Original_Title,Original_Domain,Original_Job_Description,Original_Requirements,Original_Company
0,VN0001,Fresher Product Owner,Excel; UX; UI; Agile,0.0,Phát triển phần mềm,"Xác định yêu cầu: Trực tiếp làm việc, đảm bảo hoàn thiện các tài liệu liên quan đến phát triển s...",Fresher Product Owner,True,Dưới 1 năm,Software Development,...,CC-BY-NC-4.0,https://huggingface.co/datasets/tinixai/vietnamese-job-descriptions/viewer/default/train?row=4289,3d5307608a76ac9130d57a85325e1c962fca02d3e68fc018712cc4aecd393c75,experience_level,NaN,Fresher Product Owner,Phát triển phần mềm,"Xác định yêu cầu: Trực tiếp làm việc, đảm bảo hoàn thiện các tài liệu liên quan đến phát triển s...","Đã từng tham gia vào các dự án công nghệ hoặc phát triển sản phẩm. - Có khả năng self- study, re...",APERO TECHNOLOGIES GROUP
1,VN0002,Fullstack Java Developer,SQL; MySQL; SQL Server; MongoDB; Oracle; Java; Spring; Hibernate; React; Angular,2.0,Phát triển phần mềm,Thực hiện đúng chế độ lập kế hoạch và báo cáo công việc theo quy định. Làm việc trên Database My...,Fullstack Java Developer,True,Không,Software Development,...,CC-BY-NC-4.0,https://huggingface.co/datasets/tinixai/vietnamese-job-descriptions/viewer/default/train?row=4153,f4e61c688227ad049de7bc82cb446005f089e577f6358940f16b93ba0252865e,requirements,toi thieu 2 nam kinh nghiem,Fullstack Java Developer,Phát triển phần mềm,Thực hiện đúng chế độ lập kế hoạch và báo cáo công việc theo quy định. Làm việc trên Database My...,Kinh nghiệm làm việc: +) Tối thiểu 2 năm kinh nghiệm +) Có khả năng phân tích yêu cầu khách hàng...,CÔNG TY CP CÔNG NGHỆ VÀ TRUYỀN THÔNG DAGORAS
2,VN0003,Lập Trình Nhúng-Embedded Software Engineer (C/C++),JavaScript; C++; Linux; Networking; Embedded,4.0,Phát triển phần mềm nhúng,"VĂN PHÒNG ĐẠI DIỆN KAON GROUP CO., LTD TẠI THÀNH PHỐ HÀ NỘI tuyển vị trí Lập trình viên nhúng tạ...",Embedded Software Engineer (C++),True,4 năm,Embedded Software,...,CC-BY-NC-4.0,https://huggingface.co/datasets/tinixai/vietnamese-job-descriptions/viewer/default/train?row=9,8f22e39d0728737f6ea627ed55994fce9f747cadee38bf989773daffaeb8caf4,experience_level,NaN,Lập Trình Nhúng-Embedded Software Engineer (C/C++),Phát triển phần mềm nhúng,Responsibilities: Verify and troubleshoot WiFi issues and tuning WiFi performance. Customize WiF...,Strong in C/C++ development in embedded Linux Minimum 2 years working in network or telecommunic...,"VĂN PHÒNG ĐẠI DIỆN KAON GROUP CO., LTD TẠI THÀNH PHỐ HÀ NỘI"
3,VN0004,Backend Developer (NodeJS),SQL; PostgreSQL; MySQL; MongoDB; Redis; TypeScript; Node.js; AWS; GCP; Agile; Embedded,3.0,Phát triển phần mềm,Mô tả công việc - Tham gia vào các buổi review code để đảm bảo chất lượng code và bổ sung kiến t...,Backend Developer (NodeJS),True,Không,Software Development,...,CC-BY-NC-4.0,https://huggingface.co/datasets/tinixai/vietnamese-job-descriptions/viewer/default/train?row=4094,f6a3b5050839b255dcaeb5ded9ec3e49066dae9890fbb2b6d699bb8111197ff9,job_description,"- tu 3- 4 nam kinh nghiem, thanh thao cac cong nghe va ngon ngu lap trinh backend (nodejs, types...",Backend Developer (NodeJS),Phát triển phần mềm,Mô tả công việc - Tham gia vào các buổi review code để đảm bảo chất lượng code và bổ sung kiến t...,NaN,UNSTATIC
4,VN0005,Software Quality Assurance (SQA) Engineer,UX; Jira,1.0,Đảm bảo chất lượng phần mềm,KOH YOUNG TECHNOLOGY INC. VIETNAM tuyển vị trí Kỹ sư kiểm thử phần mềm tại Hà Nội. Lĩnh vực: Đảm...,Software Quality Assurance (SQA) Engineer,True,1 năm,Quality Assurance,...,CC-BY-NC-4.0,https://huggingface.co/datasets/tinixai/vietnamese-job-descriptions/viewer/default/train?row=3871,1cc37ed8d483432805570b0c9e4cd6ea446709a914d2678f6a684a0afca2f7b0,experience_level,NaN,Software Quality Assurance (SQA) Engineer,Đảm bảo chất lượng phần mềm,We are looking for a meticulous SQA Engineer to ensure the quality of our 3D inspection software...,Experience: 1+ years of experience in Software Testing/QA (Freshers with strong logical thinking...,KOH YOUNG TECHNOLOGY INC. VIETNAM
5,VN0006,Kỹ Sư Lập Trình Frontend,SQL; REST API; JavaScript; React; C++; Dart; Flutter; Android; Networking; UX; UI,0.0,Phát triển phần mềm,"Lập trình giao diện WEB- APP cho hệ thống quản lý robot, xe tự hành (AGV/AMR); - Phát triển giao...","Frontend Developer (SQL, React, C++)",False,Không,Software Development,...,CC-BY-NC-4.0,https://huggingface.co/datasets/tinixai/vietnamese-job-descriptions/viewer/default/train?row=1314,49ec97a48775b18cc2309080ade059262abf764d63f438837916ed967962ccfe,unknown,NaN,Kỹ Sư Lập Trình Frontend,Phát triển phần mềm,"Lập trình giao diện WEB- APP cho hệ thống quản lý robot, xe tự hành (AGV/AMR); - Phát triển giao...","Có kiến thức nền tảng lập trình, tư duy đối tượng cơ bản (OOP); - Có kiến thức về lập trình fron...",CÔNG TY CỔ PHẦN RTC TECHNOLOGY VIỆT NAM
6,VN0007,[Hybrid] Business Analyst,Figma; Agile; Scrum; Jira,3.0,Phân tích nghiệp vụ,CÔNG TY CỔ PHẦN IGNIFY tuyển vị trí Chuyên viên phân tích nghiệp vụ tại Hà Nội. Lĩnh vực: Phân t...,[Hybrid] Business Analyst,True,3 năm,Business Analysis,...,CC-BY-NC-4.0,https://huggingface.co/datasets/tinixai/vietnamese-job-descriptions/viewer/default/train?row=185,a63f33daa458eb73fcf0385a89ea7d38be174b29bf1491754371409393dd5cb4,experience_level,NaN,[Hybrid] Business Analyst,Phân tích nghiệp vụ,Act as the communication bridge between clients and technical teams. Collaborate with project ma...,3 years of experience as a Business Analyst in IT/software projects. Experience in banking/finan...,CÔNG TY CỔ PHẦN IGNIFY
7,VN0008,Mobile/ Flutter Intern,Java; JavaScript; Kotlin; Swift; Dart; Flutter; Firebase; Android; iOS; Docker; CI/CD; Git; UX; UI,0.0,Phát triển ứng dụng di động,LINAGORA tuyển vị trí Lập trình viên di động tại Hà Nội. Lĩnh vực: Phát triển ứng dụng di động. ...,Mobile/ Flutter Intern,False,Không,Mobile Development,...,CC-BY-NC-4.0,https://huggingface.co/datasets/tinixai/vietnamese-job-descriptions/viewer/default/train?row=4271,f71acc8db0a8080539541fa1ab43b366e40761f22015ab92757b5c287adb43bd,unknown,NaN,Mobile/ Flutter Intern,Phát triển ứng dụng di động,"OVERVIEW Twake Mail ( mail.com) is an OpenSource, modern, and secure email solution built with F...",NaN,LINAGORA
8,VN0009,DevOps Engineer,Docker; Kubernetes; CI/CD; Git; Jenkins; Security; Networking,1.0,Hạ tầng điện toán đám mây,"Xử lý sự cố, khắc phục lỗi và đưa ra các giải pháp cải tiến. Tự động hóa các quy trình triển kha...",DevOps Engineer,True,1 năm,Cloud Infrastructure,...,CC-BY-NC-4.0,https://huggingface.co/datasets/tinixai/vietnamese-job-descriptions/viewer/default/train?row=4429,c58a62c09f15aad6222f16f19f4d8d89c19999fba523db812a1f66d948e462f4,experience_level,NaN,DevOps Engineer,Hạ tầng điện toán đám mây,"Xử lý sự cố, khắc phục lỗi và đưa ra các giải pháp cải tiến. Tự động hóa các quy trình triển kha...","Có kiến thức về networking, security, và cloud computing. Kỹ năng giao tiếp và giải quyết vấn đề...",CÔNG TY CỔ PHẦN THANH TOÁN G
9,VN0010,Data Engineer,Python; SQL; Docker; AWS; GCP; Airflow; ETL; dbt; Security,1.0,Kỹ thuật dữ liệu,MÔ TẢ CÔNG VIỆC Phối hợp cùng Data Analyst và Data Scientist để cung cấp dữ liệu phục vụ phân tí...,Data Engineer,True,Không,Data Engineering,...,CC-BY-NC-4.0,https://huggingface.co/datasets/tinixai/vietnamese-job-descriptions/viewer/default/train?row=4538,987212f214b4fe124315582279740326863ca13447ae6569b7d7ce0e3f2a3c91,job_description,– kinh nghiem: * must- have: toi thieu 1 nam kinh nghiem lam viec voi data pipeline.,Data Engineer,Kỹ thuật dữ liệu,MÔ TẢ CÔNG VIỆC Phối hợp cùng Data Analyst và Data Scientist để cung cấp dữ liệu phục vụ phân tí...,NaN,CÔNG TY CP CÔNG NGHỆ GIÁO DỤC TRƯỜNG HỌC TRỰC TUYẾN - ONSCHOOL

### 3. Chuẩn bị ba CV để chạy thử

Ba hồ sơ giả lập lần lượt thuộc nhóm phân tích dữ liệu, backend Python và AI/NLP.
CV được viết cùng ngôn ngữ với tin vì TF-IDF không tự dịch từ ngữ.
Đây là dữ liệu minh họa, không phải hồ sơ ứng viên thật.

In [3]:
resumes_vi = [
    {
        "Resume_ID": "CV001", "Profile": "Ứng viên phân tích dữ liệu",
        "CV_Text": "Tôi có 1 năm kinh nghiệm phân tích dữ liệu. Tôi sử dụng SQL, Python và Pandas "
                   "để làm sạch và phân tích dữ liệu bán hàng, khách hàng. Tôi xây dựng bảng điều "
                   "khiển Power BI, báo cáo Excel và giải thích xu hướng kinh doanh, chỉ số KPI. "
                   "Tôi mong muốn làm chuyên viên phân tích dữ liệu hoặc phân tích dữ liệu kinh doanh."
    },
    {
        "Resume_ID": "CV002", "Profile": "Ứng viên backend Python",
        "CV_Text": "Tôi là lập trình viên Backend Python có 2 năm kinh nghiệm phát triển phần mềm. "
                   "Tôi xây dựng dịch vụ REST API bằng FastAPI và Django, thiết kế cơ sở dữ liệu "
                   "PostgreSQL và triển khai xác thực người dùng. Tôi viết kiểm thử đơn vị, "
                   "đóng gói dịch vụ bằng Docker và phối hợp với lập trình viên giao diện."
    },
    {
        "Resume_ID": "CV003", "Profile": "Ứng viên AI và xử lý ngôn ngữ",
        "CV_Text": "Tôi là kỹ sư trí tuệ nhân tạo có 2 năm kinh nghiệm. Tôi sử dụng Python, "
                   "PyTorch và Transformers cho xử lý ngôn ngữ tự nhiên, phân loại văn bản. "
                   "Tôi đã xây dựng tìm kiếm ngữ nghĩa, véc-tơ biểu diễn tài liệu và hệ gợi ý. "
                   "Tôi triển khai dịch vụ dự đoán của mô hình học máy bằng FastAPI và Docker."
    },
]

if LANGUAGE == "vi":
    resumes = resumes_vi
else:
    resumes_path = DATA_DIR / "resumes.json"
    resumes = (
        json.loads(resumes_path.read_text(encoding="utf-8"))
        if resumes_path.exists() else generator.create_resumes()
    )

display(pd.DataFrame(resumes))

,Resume_ID,Profile,CV_Text
0,CV001,Ứng viên phân tích dữ liệu,"Tôi có 1 năm kinh nghiệm phân tích dữ liệu. Tôi sử dụng SQL, Python và Pandas để làm sạch và phâ..."
1,CV002,Ứng viên backend Python,Tôi là lập trình viên Backend Python có 2 năm kinh nghiệm phát triển phần mềm. Tôi xây dựng dịch...
2,CV003,Ứng viên AI và xử lý ngôn ngữ,"Tôi là kỹ sư trí tuệ nhân tạo có 2 năm kinh nghiệm. Tôi sử dụng Python, PyTorch và Transformers ..."

### 4. Giai đoạn 2 — từ văn bản đến điểm tương đồng

Quy trình: **ghép nội dung tin → chuẩn hóa → vector hóa → cosine similarity → xếp hạng**.

- Ghép chức danh, kỹ năng, kinh nghiệm, lĩnh vực và mô tả; bỏ Job_ID khỏi đặc trưng.
- TF-IDF dùng unigram/bigram, học từ vựng từ tin tuyển dụng. CV chỉ được `transform`,
  không `fit` lại, để giữ cùng không gian vector.
- Sentence Transformers dùng mô hình pretrained để biểu diễn ngữ nghĩa.

$$\mathrm{cosine}(q,j) = \frac{q \cdot j}{\|q\|_2\,\|j\|_2}$$

Điểm lớn hơn biểu thị nội dung gần nhau hơn. Điểm không phải xác suất trúng tuyển.
Kinh nghiệm hiện là tín hiệu văn bản, chưa được kiểm tra như điều kiện tuyển dụng bắt buộc.
Ô tiếp theo minh họa công thức với hai văn bản ngắn, không phải evaluation mô hình.

In [4]:
example_texts = [
    "SQL Python Pandas phân tích dữ liệu",
    "SQL Power BI phân tích dữ liệu kinh doanh",
]
example_encoder = TfidfTextVectorizer()
example_vectors = example_encoder.fit_transform(example_texts)
example_score = cosine_similarity(example_vectors[0:1], example_vectors[1:2])[0, 0]

print("Văn bản 1:", TextPreprocessor.normalize(example_texts[0]))
print("Văn bản 2:", TextPreprocessor.normalize(example_texts[1]))
print("Kích thước ma trận TF-IDF:", example_vectors.shape)
print(f"Cosine similarity: {example_score:.4f}")

Văn bản 1: SQL Python Pandas phân tích dữ liệu
Văn bản 2: SQL Power BI phân tích dữ liệu kinh doanh
Kích thước ma trận TF-IDF: (2, 22)
Cosine similarity: 0.3727

### 5. Xem mã nguồn OOP và khởi tạo AI Engine

Notebook tái sử dụng `JobRecommenderSystem` trong `job_recommender.py` để kết quả
nhất quán với chương trình Python. Các phương thức bên dưới là mã nguồn thật đang được chạy.
Bạn có thể mở module để xem đầy đủ bước kiểm tra dữ liệu, tiền xử lý và vector hóa.
Khi sửa module trong lúc kernel đang chạy, hãy khởi động lại kernel và chạy lại toàn bộ notebook.

In [5]:
for method in (
    JobRecommenderSystem.recommend_similar_jobs,
    JobRecommenderSystem.match_cv_to_jobs,
):
    display(Code(inspect.getsource(method), language="python"))

    def recommend_similar_jobs(self, job_id: str, top_n: int = 5, *, location: str | None = None) -> pd.DataFrame:
        """So một việc làm với tất cả việc làm khác, loại chính nó khỏi top-N.

        Raises:
            KeyError: Job_ID không tồn tại.
            ValueError: top_n không phải số nguyên dương.
        """
        self._validate_top_n(top_n)
        if not isinstance(job_id, str):
            raise TypeError("job_id phải là chuỗi, ví dụ 'J001'.")
        job_id = TextPreprocessor.normalize(job_id)
        if job_id not in self._id_to_position:
            raise KeyError(f"Không tìm thấy Job_ID: {job_id}")
        position = self._id_to_position[job_id]
        # Chỉ tính vector 1 x N, tránh lưu ma trận N x N không cần thiết.
        query_vector = self._job_vectors[position:position + 1]
        scores = cosine_similarity(query_vector, self._job_vectors).ravel()
        return self._rank(scores, top_n, exclude_position=position,
                          eligible_positions=self._eligible_positions(location))

    def match_cv_to_jobs(self, cv_text: str, top_n: int = 5, *, location: str | None = None,
                         profile: ResumeProfile | None = None) -> pd.DataFrame:
        """Lọc vùng mong muốn, rồi xếp hạng bằng 4 điểm cosine có trọng số.

        Điểm tổng = 25% vị trí + 35% kỹ năng + 15% lĩnh vực + 25% mô tả.
        Trọng số là lựa chọn baseline, chưa được tối ưu trên dữ liệu gán nhãn.
        Địa chỉ không tự động trở thành điều kiện lọc: người dùng truyền vùng
        đã chọn/xác nhận. Không dùng tuổi, giới tính, ảnh mặt hay tên để xếp hạng.
        """
        self._validate_top_n(top_n)
        if not isinstance(cv_text, str) or not cv_text.strip():
            raise ValueError("cv_text phải là chuỗi văn bản không rỗng.")
        eligible = self._eligible_positions(location)
        if not eligible:
            return self._rank(np.zeros(len(self._jobs)), top_n, eligible_positions=[])
        profile = profile or ResumeAnalyzer().analyze(cv_text)
        if profile.text != cv_text:
            raise ValueError("CV profile does not match current text")
        matching_text = profile.matching_text
        query_vector = self._encoder.transform([TextPreprocessor.normalize(matching_text)])
        if self.backend == "tfidf" and query_vector.nnz == 0:
            warnings.warn(
                "CV không có từ thuộc vocabulary TF-IDF; không có đủ tín hiệu để gợi ý.",
                UserWarning, stacklevel=2,
            )
            return self._rank(np.zeros(len(self._jobs)), top_n).iloc[:0].copy()
        queries = {
            "Title": profile.title_text or matching_text,
            "Skills": "; ".join(profile.skills) or matching_text,
            "Domain": profile.domain_text or matching_text,
            "Job_Description": matching_text,
        }
        weights = {"Title": 0.25, "Skills": 0.35, "Domain": 0.15, "Job_Description": 0.25}
        components = {
            field: cosine_similarity(self._encoder.transform([query]), self._field_vectors[field]).ravel()
            for field, query in queries.items()
        }
        scores = sum(weights[field] * values for field, values in components.items())
        # Không lấp đủ top-N bằng các việc hoàn toàn không có tín hiệu liên quan.
        eligible = [index for index in eligible if scores[index] > 0]
        result = self._rank(scores, top_n, eligible_positions=eligible, components=components)
        cv_skills = set(profile.skills)
        result["Matched_Skills"] = ["; ".join(skill for skill in extract_skills(row["Skills"]) if skill in cv_skills)
                                    for _, row in result.iterrows()]
        return result

In [6]:
# Tính vector việc làm một lần, sau đó dùng lại cho các truy vấn.
engine = JobRecommenderSystem(jobs, backend=BACKEND)
print(f"Engine đã sẵn sàng với {len(jobs)} việc làm; backend={engine.backend}.")

Engine đã sẵn sàng với 500 việc làm; backend=tfidf.

### 6. Gợi ý việc làm tương tự tin đang xem (Item-to-Item)

`recommend_similar_jobs(job_id, top_n=5)` so sánh vector tin đang xem với các tin
khác, loại chính tin đó rồi lấy top-N theo điểm giảm dần. Nếu bằng điểm, dùng Job_ID
để giữ thứ tự ổn định. Đây là gợi ý dựa trên nội dung, chưa dùng lịch sử tương tác.

In [7]:
print("Tin tuyển dụng đang xem:")
display(jobs.loc[jobs["Job_ID"] == JOB_ID])

similar_jobs = engine.recommend_similar_jobs(JOB_ID, top_n=TOP_N)
result_columns = ["Rank", "Job_ID", "Title", "Skills", "Experience_Years", "Domain", "Similarity_Score"]
print("Những việc làm tương tự:")
display(similar_jobs[result_columns].round({"Similarity_Score": 4}))

Tin tuyển dụng đang xem:

,Job_ID,Title,Skills,Experience_Years,Domain,Job_Description,Title_EN,Experience_Known,Experience_Text,Domain_EN,...,Source_License,Source_URL,Content_Fingerprint,Experience_Source,Experience_Evidence,Original_Title,Original_Domain,Original_Job_Description,Original_Requirements,Original_Company
15,VN0016,Data Analyst & Data Scientist,Python; SQL; AWS,0.0,Phân tích dữ liệu,"Chương trình Tuyển dụng Tập sự tiềm năng- Khối Công nghệ thông tin, tiếp nhận chính thức sau 6 t...",Data Analyst & Data Scientist,True,Không,Data Analytics,...,CC-BY-NC-4.0,https://huggingface.co/datasets/tinixai/vietnamese-job-descriptions/viewer/default/train?row=4609,d134222f3f02e01f412b1ee7cc33c8feb8a3b00b24d912509b90c427e83bcb3c,requirements,"sinh vien moi tot nghiep, gpa 6.5 (kha)(hoac da di lam ≤ 1 nam kinh nghiem) thuoc cac truong dh ...",Data Analyst & Data Scientist,Phân tích dữ liệu,"Chương trình Tuyển dụng Tập sự tiềm năng- Khối Công nghệ thông tin, tiếp nhận chính thức sau 6 t...","Sinh viên mới tốt nghiệp, GPA 6.5 (Khá)(hoặc đã đi làm ≤ 1 năm kinh nghiệm) thuộc các trường ĐH ...",NGÂN HÀNG TMCP TIÊN PHONG | TPBANK

Những việc làm tương tự:

,Rank,Job_ID,Title,Skills,Experience_Years,Domain,Similarity_Score
0,1,VN0150,Chuyên Viên Phân Tích Và Thiết Kế Mô Hình Dữ Liệu - Data Analyst - Khối Dữ Liệu (HO26.76),SQL; Excel; Power BI; Tableau; SQL Server; Oracle,2.0,Phân tích dữ liệu,0.1405
1,2,VN0075,Chuyên viên Phân tích và thiết kế Mô hình dữ liệu - Data Analyst - Khối Dữ liệu (HO26.76),SQL; Excel; Power BI; Tableau; SQL Server; Oracle,2.0,Phân tích dữ liệu,0.1379
2,3,VN0146,Senior Data Engineer (Finance division) - HN - TA133,Python; SQL; Statistics; Oracle; ETL; Business Analysis,4.0,Kỹ thuật dữ liệu,0.1144
3,4,VN0336,Software engineer intern,Machine Learning; Node.js; UI,0.0,Phát triển phần mềm,0.1106
4,5,VN0136,UI UX Designer - Hà Nội - TA050,HTML; CSS; UX; UI; Agile,3.0,Thiết kế sản phẩm,0.1097

### 7. Ghép CV với việc làm

`ResumeAnalyzer` nhận diện kỹ năng/vị trí/lĩnh vực và gợi ý địa điểm. Địa chỉ nhà
không tự động là nguyện vọng làm việc: truyền `location` đã xác nhận để lọc cứng.
Sau đó tính cosine từng trường và xếp hạng:

**25% vị trí + 35% kỹ năng + 15% lĩnh vực + 25% mô tả/yêu cầu**.

Đây là trọng số baseline, chưa được tối ưu bằng Giai đoạn 3. Điểm không phải
xác suất trúng tuyển; metadata kinh nghiệm chưa phải điều kiện lọc bắt buộc.

In [8]:
all_matches = []
for resume in resumes:
    display(Markdown(f"**{resume['Resume_ID']} — {resume['Profile']}**"))
    print(resume["CV_Text"])
    matches = engine.match_cv_to_jobs(resume["CV_Text"], top_n=TOP_N)
    display(matches[result_columns].round({"Similarity_Score": 4}))
    all_matches.append(matches.assign(Resume_ID=resume["Resume_ID"]))

cv_matches = pd.concat(all_matches, ignore_index=True)

**CV001 — Ứng viên phân tích dữ liệu**

Tôi có 1 năm kinh nghiệm phân tích dữ liệu. Tôi sử dụng SQL, Python và Pandas để làm sạch và phân tích dữ liệu bán hàng, khách hàng. Tôi xây dựng bảng điều khiển Power BI, báo cáo Excel và giải thích xu hướng kinh doanh, chỉ số KPI. Tôi mong muốn làm chuyên viên phân tích dữ liệu hoặc phân tích dữ liệu kinh doanh.

,Rank,Job_ID,Title,Skills,Experience_Years,Domain,Similarity_Score
0,1,VN0328,Chuyên Viên Phân Tích Dữ Liệu,Python; SQL; Excel; Power BI,2.0,Phân tích dữ liệu,0.5180
1,2,VN0047,Chuyên Viên Phân Tích Dữ Liệu (Data Analyst),SQL; Power BI; Tableau,1.0,Phân tích dữ liệu,0.4741
2,3,VN0275,Chuyên Viên Phân Tích Dữ Liệu,Excel; Power BI; Statistics,3.0,Phân tích dữ liệu,0.4611
3,4,VN0261,Chuyên Viên Phân Tích Dữ Liệu,Python; SQL; Excel; Power BI; Tableau; Statistics; ETL; Security,2.0,Phân tích dữ liệu,0.4557
4,5,VN0315,Chuyên viên phân tích dữ liệu,Python; SQL; Power BI; Tableau; Statistics; Security,3.0,Phân tích dữ liệu,0.4185

**CV002 — Ứng viên backend Python**

Tôi là lập trình viên Backend Python có 2 năm kinh nghiệm phát triển phần mềm. Tôi xây dựng dịch vụ REST API bằng FastAPI và Django, thiết kế cơ sở dữ liệu PostgreSQL và triển khai xác thực người dùng. Tôi viết kiểm thử đơn vị, đóng gói dịch vụ bằng Docker và phối hợp với lập trình viên giao diện.

,Rank,Job_ID,Title,Skills,Experience_Years,Domain,Similarity_Score
0,1,VN0021,"Lập Trình Viên Backend Ruby, Node.Js Hoặc Python",Python; FastAPI; Django; PostgreSQL; MySQL; MongoDB; REST API; Node.js; Express; Ruby; Rails,2.0,Phát triển phần mềm,0.2898
1,2,VN0104,Backend Developer (Python),Python; FastAPI; Django; Flask; PostgreSQL; MySQL; MongoDB; REST API; GraphQL; Java; JavaScript;...,3.0,Phát triển phần mềm,0.2692
2,3,VN0324,Senior Backend Developer,Python; SQL; FastAPI; Django; PostgreSQL; MySQL; MongoDB; Redis; REST API; GraphQL; Java; Spring...,2.0,Phát triển phần mềm,0.2525
3,4,VN0440,Backend Developer,Python; FastAPI; PostgreSQL; TypeScript; Node.js; CI/CD; Git; AWS; Terraform; Security,3.0,Phát triển phần mềm,0.2419
4,5,VN0117,Backend Developer - Senior Level (Pythonl) | Tối Thiểu 2 Năm Kinh Nghiệm | Mức Lương Upto 40M,Python; SQL; FastAPI; Django; Flask; PostgreSQL; MySQL; REST API; Linux; Docker; Kubernetes; CI/...,2.0,Phát triển phần mềm,0.2103

**CV003 — Ứng viên AI và xử lý ngôn ngữ**

Tôi là kỹ sư trí tuệ nhân tạo có 2 năm kinh nghiệm. Tôi sử dụng Python, PyTorch và Transformers cho xử lý ngôn ngữ tự nhiên, phân loại văn bản. Tôi đã xây dựng tìm kiếm ngữ nghĩa, véc-tơ biểu diễn tài liệu và hệ gợi ý. Tôi triển khai dịch vụ dự đoán của mô hình học máy bằng FastAPI và Docker.

,Rank,Job_ID,Title,Skills,Experience_Years,Domain,Similarity_Score
0,1,VN0341,AI Engineer,Python; NLP; Machine Learning,1.0,Trí tuệ nhân tạo,0.3678
1,2,VN0231,AI Engineer (Senior),Python; PyTorch; TensorFlow; NLP; Deep Learning; Machine Learning; FastAPI; MySQL; MongoDB; Agil...,2.0,Trí tuệ nhân tạo,0.3478
2,3,VN0011,AI Engineer,Python; SQL; PyTorch; TensorFlow; NLP; Machine Learning; REST API; Git; AWS; Azure; GCP,0.0,Trí tuệ nhân tạo,0.3333
3,4,VN0474,AI Engineer Intern,Python; Deep Learning; Machine Learning; FastAPI; Linux; Docker; Git,0.0,Trí tuệ nhân tạo,0.3130
4,5,VN0263,AI Engineer Intern,Python; Deep Learning; Machine Learning; FastAPI; Linux; Docker; Git,0.0,Trí tuệ nhân tạo,0.3101

### 8. Thử CV và vùng làm việc

Sửa `my_cv` hoặc `TARGET_REGION` rồi chạy lại. Nếu muốn đọc tệp, đặt `CV_FILE`
thành đường dẫn ảnh/PDF/Word .docx và cài `requirements-web.txt` trước. OCR chạy
trên máy; lần đầu tải trọng số công khai. Kiểm tra vùng gợi ý trước khi tìm.
Chỉ dùng CV mẫu nếu bạn định lưu/chia sẻ output của notebook công khai.

In [9]:
my_cv = (
    "Vị trí ứng tuyển: Lập trình viên Backend Python\n"
    "Địa chỉ: Sài Gòn\nNơi muốn làm việc: Hà Nội\n"
    "Kỹ năng: Python, FastAPI, Django, PostgreSQL, SQL, Docker.\n"
    "Tôi có 2 năm phát triển REST API, xác thực người dùng và tối ưu cơ sở dữ liệu."
    if LANGUAGE == "vi" else
    "Target role: Python Backend Developer\nPreferred location: Hanoi\n"
    "Python, FastAPI, Django, PostgreSQL, SQL, Docker; 2 years developing REST API services."
)
CV_FILE = None  # Ví dụ Path("cv.docx"); mặc định không đọc file cá nhân.
if CV_FILE is not None:
    from cv_documents import ResumeDocumentReader
    file_path = Path(CV_FILE)
    document = ResumeDocumentReader().read(file_path.read_bytes(), file_path.name)
    my_cv = document.text
    profile = ResumeAnalyzer().analyze(my_cv, ocr=document.used_ocr)
else:
    profile = ResumeAnalyzer().analyze(my_cv)

print("Kỹ năng nhận diện:", ", ".join(profile.skills))
print("Vùng gợi ý cần xác nhận:", profile.location_candidates)
location = TARGET_REGION if "Region_Codes" in jobs else None
regional_matches = engine.match_cv_to_jobs(my_cv, top_n=TOP_N, location=location, profile=profile)
display(regional_matches[result_columns].round({"Similarity_Score": 4}))
if location:
    assert regional_matches["Region_Codes"].map(lambda codes: location in str(codes).split(";")).all()

Kỹ năng nhận diện: Python, SQL, FastAPI, Django, PostgreSQL, REST API, Docker
Vùng gợi ý cần xác nhận: ('ha_noi',)

,Rank,Job_ID,Title,Skills,Experience_Years,Domain,Similarity_Score
0,1,VN0104,Backend Developer (Python),Python; FastAPI; Django; Flask; PostgreSQL; MySQL; MongoDB; REST API; GraphQL; Java; JavaScript;...,3.0,Phát triển phần mềm,0.3191
1,2,VN0021,"Lập Trình Viên Backend Ruby, Node.Js Hoặc Python",Python; FastAPI; Django; PostgreSQL; MySQL; MongoDB; REST API; Node.js; Express; Ruby; Rails,2.0,Phát triển phần mềm,0.3054
2,3,VN0091,Lập trình viên Backend,Python; Java; Spring Boot; Spring; Kubernetes; CI/CD; Git; Azure; Postman; Security,2.0,Phát triển phần mềm,0.2807
3,4,VN0117,Backend Developer - Senior Level (Pythonl) | Tối Thiểu 2 Năm Kinh Nghiệm | Mức Lương Upto 40M,Python; SQL; FastAPI; Django; Flask; PostgreSQL; MySQL; REST API; Linux; Docker; Kubernetes; CI/...,2.0,Phát triển phần mềm,0.2711
4,5,VN0065,Backend Developer,PostgreSQL; MySQL; MongoDB; Redis; React; Vue; PHP; Laravel; Docker; CI/CD; AWS; GCP; Kafka; Agi...,2.0,Phát triển phần mềm,0.2683

### 9. Kiểm tra kết quả và lưu bảng

Các kiểm tra dưới đây chỉ xác nhận hành vi phần mềm: loại tin gốc, số dòng và thứ tự
xếp hạng. Chúng không chứng minh độ chính xác gợi ý trên dữ liệu thực và không thay
thế Giai đoạn 3. Kết quả notebook được lưu riêng theo ngôn ngữ và backend.

In [10]:
assert JOB_ID not in similar_jobs["Job_ID"].tolist()
assert len(similar_jobs) == min(TOP_N, len(jobs) - 1)
assert similar_jobs["Similarity_Score"].is_monotonic_decreasing
assert np.isfinite(cv_matches["Similarity_Score"]).all()
for _, group in cv_matches.groupby("Resume_ID"):
    assert group["Similarity_Score"].is_monotonic_decreasing

output_dir = Path("outputs") / "notebook" / LANGUAGE / BACKEND
output_dir.mkdir(parents=True, exist_ok=True)
similar_jobs.to_csv(output_dir / "similar_jobs.csv", index=False, encoding="utf-8-sig")
cv_matches.to_csv(output_dir / "cv_matches.csv", index=False, encoding="utf-8-sig")
print("Các kiểm tra chức năng đều đạt.")
print(f"Đã lưu hai bảng kết quả tại: {output_dir.as_posix()}")

Các kiểm tra chức năng đều đạt.
Đã lưu hai bảng kết quả tại: outputs/notebook/vi/tfidf

### 10. Tùy chọn: Sentence Transformers

Để thử semantic embedding, cài thêm thư viện trong terminal của thư mục dự án:

```powershell
.\.venv\Scripts\python.exe -m pip install -r requirements-semantic.txt
```

Sau đó sửa `BACKEND = "sentence-transformers"` ở ô cấu hình và khởi động lại kernel,
chạy lại tất cả các ô. Lần đầu cần mạng để tải trọng số từ Hugging Face.
Notebook không tự cài thư viện hoặc tự tải model khi chạy mặc định bằng TF-IDF.
Các ví dụ phía trên lưu kết quả **TF-IDF**. Semantic thật đã được chạy riêng trong bộ đánh giá A/B/C bên dưới.

### Nhận xét để trình bày

- Catalog gồm 500 tin tham khảo từ nguồn công khai; 20 tin mock vẫn dùng cho kiểm thử. Tin chưa được xác nhận còn tuyển.
- TF-IDF phản ánh độ trùng từ/cụm từ; không tự hiểu mọi từ đồng nghĩa hay dịch giữa các ngôn ngữ.
- Số năm kinh nghiệm chưa là bộ lọc cứng; top-N vẫn có thể chứa việc làm không đủ điều kiện.
- Chưa có ngưỡng chấp nhận; một tin trong top-N có thể có mức phù hợp thấp.
- Web Streamlit đã có tải CV, OCR và lọc vùng. Bước tiếp theo là ground truth và metrics (Giai đoạn 3).

### Tài liệu tham khảo

- [Jupyter: cài đặt và khởi chạy](https://jupyter.org/install)
- [scikit-learn: TF-IDF](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html)
- [scikit-learn: cosine similarity](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html)
- [Sentence Transformers: mô hình multilingual MiniLM](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2)

### 11. Năm cải tiến của phiên bản 2

1. Kết hợp TF-IDF và semantic embedding đa ngôn ngữ.
2. Nhận diện số năm kinh nghiệm được nêu rõ, giảm điểm mềm khi thiếu năm. Không rõ khác 0 năm.
3. Đối chiếu kỹ năng được nhắc/bắt buộc/ưu tiên; giải thích đã thấy và chưa thấy trong CV.
4. Chỉ lấy một đại diện tin gần trùng; ưu tiên đa dạng công ty khi điểm gần nhau.
5. Đánh giá A TF-IDF / B semantic / C hybrid với qrels đóng băng, chia dev/test theo hồ sơ.

Lọc vùng trước xếp hạng; nguyện vọng vị trí được ghi rõ được tôn trọng. Không lấp đủ top N bằng tin ngoài vùng hoặc sai nguyện vọng.

**Công thức khởi điểm:** 0,15 từ khóa + 0,25 ngữ nghĩa + 0,30 kỹ năng + 0,15 vị trí + 0,05 lĩnh vực + 0,10 kinh nghiệm.
Thiếu thành phần nào thì bỏ trọng số đó và chuẩn hóa lại; điểm không phải xác suất trúng tuyển.

Ví dụ mặc định chạy nhẹ, không tải model. Để chạy đủ semantic, cài `requirements-semantic.txt`, đổi cờ bên dưới thành `True`.
Xem `docs/ALGORITHM_V2.md` để giải thích thuật toán và các giới hạn khi viết báo cáo.

In [11]:
from hybrid_recommender import HybridJobRecommenderSystem

USE_SEMANTIC_V2 = False  # True: có semantic; lần đầu cần tải pretrained model.
hybrid = HybridJobRecommenderSystem(jobs, use_semantic=USE_SEMANTIC_V2)
cv_v2 = (
    "Vị trí ứng tuyển: Backend Python Developer.\n"
    "Tổng kinh nghiệm: 2 năm.\n"
    "Kỹ năng: Python, Django, FastAPI, SQL, PostgreSQL, Docker, Git, REST API.\n"
    "Địa chỉ: TP. Hồ Chí Minh.\n"
    "Nơi muốn làm việc: Hà Nội."
)
profile_v2 = ResumeAnalyzer().analyze(cv_v2)
print("Kinh nghiệm:", profile_v2.experience_years, "năm; trạng thái:", profile_v2.experience_status)
print("Vùng ưu tiên:", profile_v2.location_candidates, "| Kỹ năng:", profile_v2.skills)

matches_v2 = hybrid.match_cv_to_jobs(cv_v2, top_n=5, location="ha_noi", profile=profile_v2)
columns_v2 = ["Rank", "Job_ID", "Title", "Similarity_Score", "Score_Lexical", "Score_Semantic",
              "Score_Skills", "Score_Title", "Score_Domain", "Score_Experience", "Experience_Status",
              "Matched_Skills", "Not_Mentioned_Skills", "Missing_Required_Skills", "Component_Weights"]
display(matches_v2[columns_v2].round(4))
print("Semantic:", hybrid.semantic_status, "| Số kết quả:", len(matches_v2))
if len(matches_v2):
    # Kiểm tra công thức bằng trọng số thực tế (semantic/kinh nghiệm có thể bị bỏ).
    for _, row in matches_v2.iterrows():
        reconstructed = sum(row["Component_Weights"][key] * row["Score_" + key]
                            for key in row["Component_Weights"])
        assert np.isclose(reconstructed, row.Similarity_Score)
    assert all("ha_noi" in str(value).split(";") for value in matches_v2.Region_Codes)

v2_dir = Path("outputs/notebook") / LANGUAGE / "hybrid"
v2_dir.mkdir(parents=True, exist_ok=True)
matches_v2.to_csv(v2_dir / "cv_matches.csv", index=False, encoding="utf-8-sig")
display(hybrid.recommend_similar_jobs(matches_v2.iloc[0].Job_ID if len(matches_v2) else JOB_ID,
                                     top_n=5, location="ha_noi")[result_columns])

Kinh nghiệm: 2.0 năm; trạng thái: explicit
Vùng ưu tiên: ('ha_noi',) | Kỹ năng: ('Python', 'SQL', 'FastAPI', 'Django', 'PostgreSQL', 'REST API', 'Docker', 'Git')

,Rank,Job_ID,Title,Similarity_Score,Score_Lexical,Score_Semantic,Score_Skills,Score_Title,Score_Domain,Score_Experience,Experience_Status,Matched_Skills,Not_Mentioned_Skills,Missing_Required_Skills,Component_Weights
0,1,VN0117,Backend Developer - Senior Level (Pythonl) | Tối Thiểu 2 Năm Kinh Nghiệm | Mức Lương Upto 40M,0.7087,0.1107,0.0,0.7163,1.00,1.0,1.0000,meets_minimum,Django; Docker; FastAPI; PostgreSQL; Python; REST API; SQL,AWS; Azure; CI/CD; Flask; GCP; Kafka; Kubernetes; Linux; MySQL; Security,,"{'Lexical': 0.19999999999999998, 'Semantic': 0.0, 'Skills': 0.39999999999999997, 'Title': 0.1999..."
1,2,VN0021,"Lập Trình Viên Backend Ruby, Node.Js Hoặc Python",0.6519,0.1359,0.0,0.5617,1.00,1.0,1.0000,meets_minimum,Django; FastAPI; PostgreSQL; Python; REST API,Express; MongoDB; MySQL; Node.js; Rails; Ruby,,"{'Lexical': 0.19999999999999998, 'Semantic': 0.0, 'Skills': 0.39999999999999997, 'Title': 0.1999..."
2,3,VN0104,Backend Developer (Python),0.6012,0.1204,0.0,0.5739,1.00,1.0,0.6065,below_minimum,Django; Docker; FastAPI; Git; PostgreSQL; Python; REST API,Angular; CSS; Flask; GraphQL; HTML; Java; JavaScript; MongoDB; MySQL; Node.js; React; Vue,Flask,"{'Lexical': 0.19999999999999998, 'Semantic': 0.0, 'Skills': 0.39999999999999997, 'Title': 0.1999..."
3,4,VN0152,Lập Trình Viên Fullstack .Net,0.5571,0.0778,0.0,0.5288,0.65,1.0,1.0000,meets_minimum,Docker; Git; PostgreSQL; Python; SQL,.NET; CSS; HTML; Java; JavaScript; MySQL; Oracle; React; SQL Server; Security,,"{'Lexical': 0.19999999999999998, 'Semantic': 0.0, 'Skills': 0.39999999999999997, 'Title': 0.1999..."
4,5,VN0128,Lập Trình Viên Fullstack,0.5539,0.1028,0.0,0.5083,0.65,1.0,1.0000,meets_minimum,Django; Git; Python; REST API; SQL,Angular; CSS; Express; Flask; HTML; JavaScript; Node.js; React; Vue,,"{'Lexical': 0.19999999999999998, 'Semantic': 0.0, 'Skills': 0.39999999999999997, 'Title': 0.1999..."

Semantic: disabled | Số kết quả: 5

,Rank,Job_ID,Title,Skills,Experience_Years,Domain,Similarity_Score
0,1,VN0128,Lập Trình Viên Fullstack,Python; SQL; Django; Flask; REST API; JavaScript; Node.js; Express; React; Vue; Angular; HTML; C...,2.0,Phát triển phần mềm,0.214183
1,2,VN0065,Backend Developer,PostgreSQL; MySQL; MongoDB; Redis; React; Vue; PHP; Laravel; Docker; CI/CD; AWS; GCP; Kafka; Agi...,2.0,Phát triển phần mềm,0.202193
2,3,VN0493,DATABASE ENGINEER / DATA ENGINEER (Senior Level),SQL; AWS; ETL; Security,4.0,Kỹ thuật dữ liệu,0.198783
3,4,VN0145,Devops Engineer,Docker; Kubernetes; CI/CD; Git; Jenkins; AWS; Azure; GCP; Terraform; Security; Networking; Agile...,3.0,Hạ tầng điện toán đám mây,0.197645
4,5,VN0137,Kỹ Sư Hệ Thống - Cloud Engineer (Database Service),Python; PostgreSQL; MongoDB; REST API; Go; CI/CD; Security,2.0,Hạ tầng điện toán đám mây,0.188858

### 12. Đánh giá A/B/C và đọc kết quả một cách thận trọng

Benchmark có **30 CV giả lập độc lập**: 10 dev, 20 test. Nhãn mức 1 (liên quan/có điều kiện), mức 2 (phù hợp mạnh) được biên soạn trước so sánh, không lấy từ điểm của mô hình. Có SHA256 kiểm tra catalog và chia nhóm hồ sơ tránh trùng giữa dev/test.

**Đây là pilot do trợ lý biên soạn, chưa được chuyên gia độc lập xác nhận.** Nhãn còn thưa; tin chưa gán nhãn bị tính 0, dù có thể hợp lý. Chưa thể kết luận độ chính xác thực tế. Không chỉnh tham số bằng tập test.

P@5 chia cho 5 kể cả trả thiếu kết quả; NDCG dùng gain `2**grade - 1`. Truy vấn không có tin phù hợp đo riêng bằng Empty Accuracy. Đếm thêm tin gần trùng, số công ty và số kết quả để thấy ảnh hưởng của việc lọc chặt.

Ô dưới đọc **kết quả đã chạy với semantic thật**, không cần tải model. Đổi `RUN_FULL_EVALUATION=True` để tính lại trên máy (cần thư viện/model, mất vài phút). Ba định dạng Word/PDF/ảnh của 10 CV tải tệp chỉ là kiểm thử chức năng, không phải 30 hồ sơ đánh giá độc lập.

In [12]:
from evaluation import ranking_metrics, load_benchmark, run_evaluation

# Minh họa có đáp án tính được bằng tay: 2/5 tin liên quan, 1/5 phù hợp mạnh.
example_metrics = ranking_metrics(["J_A", "J_C", "J_B"], {"J_A": 2, "J_B": 1}, k=5)
assert np.isclose(example_metrics["Precision@5"], 0.4)
assert np.isclose(example_metrics["StrictPrecision@5"], 0.2)
display(pd.DataFrame([example_metrics]))

benchmark_path = DATA_DIR / "evaluation/benchmark.json"
_, benchmark_queries = load_benchmark(benchmark_path, jobs)
print("Số hồ sơ:", len(benchmark_queries), "| Dev:", sum(q.split=="dev" for q in benchmark_queries),
      "| Test:", sum(q.split=="test" for q in benchmark_queries))

RUN_FULL_EVALUATION = False
evaluation_dir = Path("outputs/evaluation/test")
if RUN_FULL_EVALUATION:
    run_evaluation(evaluation_dir, split="test", semantic=True)
if (evaluation_dir / "summary.csv").exists():
    evaluation_summary = pd.read_csv(evaluation_dir / "summary.csv")
    display(evaluation_summary.round(4))
    print("TF-IDF hiện đạt P@5/NDCG@5 cao hơn hybrid trên pilot này.")
    print("Hybrid lọc chặt hơn; cần nhãn độc lập, đầy đủ hơn để quyết định mô hình triển khai.")
else:
    print("Chưa có báo cáo đã lưu; chạy evaluation.py theo README hoặc bật RUN_FULL_EVALUATION.")

   Precision@5  StrictPrecision@5  Recall@5   NDCG@5  MRR@5
0          0.4                0.2       1.0  0.96394    1.0

Số hồ sơ: 30 | Dev: 10 | Test: 20

,model,split,queries,positive_queries,Precision@5,StrictPrecision@5,Recall@5,NDCG@5,MRR@5,Empty_Accuracy,Region_Violations,Mean_Unique_Companies,Mean_Near_Duplicate_Extras,Mean_Returned,JudgedCoverage@5,Median_Latency_ms,Setup_seconds
0,A_tfidf,test,20,19,0.7474,0.4105,0.6083,0.8456,0.9386,1.0,0,4.50,0.1,4.75,0.7474,35.6162,2.5968
1,B_semantic,test,20,19,0.7053,0.3789,0.5830,0.7553,0.9474,1.0,0,4.45,0.1,4.75,0.7053,258.6268,455.4623
2,C_hybrid,test,20,19,0.6316,0.4105,0.4771,0.7919,0.9211,1.0,0,3.70,0.0,3.85,0.7684,288.7727,12.2440

TF-IDF hiện đạt P@5/NDCG@5 cao hơn hybrid trên pilot này.
Hybrid lọc chặt hơn; cần nhãn độc lập, đầy đủ hơn để quyết định mô hình triển khai.